language: bash

env:
  global:
    - GIT_AUTHOR_EMAIL=t.omura8383@gmail.com
    - GIT_AUTHOR_NAME=dais0n
    - HUGO_VERSION=0.30.2
    - secure: "a5943e31f75305721a0789e470a8e2f5df3d0448"
    - GIT_URL=https://${GH_TOKEN}@github.com/${GIT_AUTHOR_NAME}/blog.git

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz

before_deploy:
  - git remote set-url origin ${GIT_URL}
  - git fetch origin gh-pages:remotes/origin/gh-pages
  - git worktree add -B gh-pages public origin/gh-pages
  - ./hugo

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
