baseURL = "https://blog.dais0n.net"
languageCode = "en-us"
title = "dais0nNote"
theme = "hucore"
hasCJKLanguage = true
googleAnalytics = "UA-111937976-1"
disqusShortname = "blog-dais0n-net"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "dais0nNote"
keywords = ["dais0nNote"]
author = "Takuya Omura"
sharingicons = true

[[params.social]]
url = "https://github.com/dais0n"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/dais0n_"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://www.instagram.com/dais0n_"
fa_icon = "fa-instagram"
