baseURL = "https://dais0n.github.io/blog"
languageCode = "en-us"
title = "dais0nMemo"
theme = "hucore"
hasCJKLanguage = true
googleAnalytics = "UA-111937976-1"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "dais0nMemo"
keywords = ["dais0nMemo"]
author = "Takuya Omura"
sharingicons = true

[[params.social]]
url = "https://github.com/dais0n"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/daison8383"
fa_icon = "fa-twitter"
